package com.example.nvdovin.weatherapp.GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.nvdovin.weatherapp.model.City;
import com.example.nvdovin.weatherapp.model.Clouds;
import com.example.nvdovin.weatherapp.model.Coord;
import com.example.nvdovin.weatherapp.model.Main;
import com.example.nvdovin.weatherapp.model.Rain;
import com.example.nvdovin.weatherapp.model.Sys;
import com.example.nvdovin.weatherapp.model.Sys_;
import com.example.nvdovin.weatherapp.model.Weather;
import com.example.nvdovin.weatherapp.model.WeatherList;
import com.example.nvdovin.weatherapp.model.Wind;

import com.example.nvdovin.weatherapp.GreenDao.CityDao;
import com.example.nvdovin.weatherapp.GreenDao.CloudsDao;
import com.example.nvdovin.weatherapp.GreenDao.CoordDao;
import com.example.nvdovin.weatherapp.GreenDao.MainDao;
import com.example.nvdovin.weatherapp.GreenDao.RainDao;
import com.example.nvdovin.weatherapp.GreenDao.SysDao;
import com.example.nvdovin.weatherapp.GreenDao.Sys_Dao;
import com.example.nvdovin.weatherapp.GreenDao.WeatherDao;
import com.example.nvdovin.weatherapp.GreenDao.WeatherListDao;
import com.example.nvdovin.weatherapp.GreenDao.WindDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig cloudsDaoConfig;
    private final DaoConfig coordDaoConfig;
    private final DaoConfig mainDaoConfig;
    private final DaoConfig rainDaoConfig;
    private final DaoConfig sysDaoConfig;
    private final DaoConfig sys_DaoConfig;
    private final DaoConfig weatherDaoConfig;
    private final DaoConfig weatherListDaoConfig;
    private final DaoConfig windDaoConfig;

    private final CityDao cityDao;
    private final CloudsDao cloudsDao;
    private final CoordDao coordDao;
    private final MainDao mainDao;
    private final RainDao rainDao;
    private final SysDao sysDao;
    private final Sys_Dao sys_Dao;
    private final WeatherDao weatherDao;
    private final WeatherListDao weatherListDao;
    private final WindDao windDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        cloudsDaoConfig = daoConfigMap.get(CloudsDao.class).clone();
        cloudsDaoConfig.initIdentityScope(type);

        coordDaoConfig = daoConfigMap.get(CoordDao.class).clone();
        coordDaoConfig.initIdentityScope(type);

        mainDaoConfig = daoConfigMap.get(MainDao.class).clone();
        mainDaoConfig.initIdentityScope(type);

        rainDaoConfig = daoConfigMap.get(RainDao.class).clone();
        rainDaoConfig.initIdentityScope(type);

        sysDaoConfig = daoConfigMap.get(SysDao.class).clone();
        sysDaoConfig.initIdentityScope(type);

        sys_DaoConfig = daoConfigMap.get(Sys_Dao.class).clone();
        sys_DaoConfig.initIdentityScope(type);

        weatherDaoConfig = daoConfigMap.get(WeatherDao.class).clone();
        weatherDaoConfig.initIdentityScope(type);

        weatherListDaoConfig = daoConfigMap.get(WeatherListDao.class).clone();
        weatherListDaoConfig.initIdentityScope(type);

        windDaoConfig = daoConfigMap.get(WindDao.class).clone();
        windDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        cloudsDao = new CloudsDao(cloudsDaoConfig, this);
        coordDao = new CoordDao(coordDaoConfig, this);
        mainDao = new MainDao(mainDaoConfig, this);
        rainDao = new RainDao(rainDaoConfig, this);
        sysDao = new SysDao(sysDaoConfig, this);
        sys_Dao = new Sys_Dao(sys_DaoConfig, this);
        weatherDao = new WeatherDao(weatherDaoConfig, this);
        weatherListDao = new WeatherListDao(weatherListDaoConfig, this);
        windDao = new WindDao(windDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Clouds.class, cloudsDao);
        registerDao(Coord.class, coordDao);
        registerDao(Main.class, mainDao);
        registerDao(Rain.class, rainDao);
        registerDao(Sys.class, sysDao);
        registerDao(Sys_.class, sys_Dao);
        registerDao(Weather.class, weatherDao);
        registerDao(WeatherList.class, weatherListDao);
        registerDao(Wind.class, windDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        cloudsDaoConfig.clearIdentityScope();
        coordDaoConfig.clearIdentityScope();
        mainDaoConfig.clearIdentityScope();
        rainDaoConfig.clearIdentityScope();
        sysDaoConfig.clearIdentityScope();
        sys_DaoConfig.clearIdentityScope();
        weatherDaoConfig.clearIdentityScope();
        weatherListDaoConfig.clearIdentityScope();
        windDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public CloudsDao getCloudsDao() {
        return cloudsDao;
    }

    public CoordDao getCoordDao() {
        return coordDao;
    }

    public MainDao getMainDao() {
        return mainDao;
    }

    public RainDao getRainDao() {
        return rainDao;
    }

    public SysDao getSysDao() {
        return sysDao;
    }

    public Sys_Dao getSys_Dao() {
        return sys_Dao;
    }

    public WeatherDao getWeatherDao() {
        return weatherDao;
    }

    public WeatherListDao getWeatherListDao() {
        return weatherListDao;
    }

    public WindDao getWindDao() {
        return windDao;
    }

}
