package com.example.nvdovin.weatherapp.GreenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.nvdovin.weatherapp.model.Wind;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WIND".
*/
public class WindDao extends AbstractDao<Wind, Long> {

    public static final String TABLENAME = "WIND";

    /**
     * Properties of entity Wind.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Speed = new Property(1, Double.class, "speed", false, "SPEED");
        public final static Property Deg = new Property(2, Double.class, "deg", false, "DEG");
    }


    public WindDao(DaoConfig config) {
        super(config);
    }
    
    public WindDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WIND\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SPEED\" REAL," + // 1: speed
                "\"DEG\" REAL);"); // 2: deg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WIND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Wind entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double speed = entity.getSpeed();
        if (speed != null) {
            stmt.bindDouble(2, speed);
        }
 
        Double deg = entity.getDeg();
        if (deg != null) {
            stmt.bindDouble(3, deg);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Wind entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double speed = entity.getSpeed();
        if (speed != null) {
            stmt.bindDouble(2, speed);
        }
 
        Double deg = entity.getDeg();
        if (deg != null) {
            stmt.bindDouble(3, deg);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Wind readEntity(Cursor cursor, int offset) {
        Wind entity = new Wind( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // speed
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2) // deg
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Wind entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSpeed(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setDeg(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Wind entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Wind entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Wind entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
