package com.example.nvdovin.weatherapp.database.dao;

import com.example.nvdovin.weatherapp.database.model.City;
import com.example.nvdovin.weatherapp.database.model.WeatherData;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig weatherDataDaoConfig;

    private final CityDao cityDao;
    private final WeatherDataDao weatherDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        weatherDataDaoConfig = daoConfigMap.get(WeatherDataDao.class).clone();
        weatherDataDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        weatherDataDao = new WeatherDataDao(weatherDataDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(WeatherData.class, weatherDataDao);
    }

    public void clear() {
        cityDaoConfig.clearIdentityScope();
        weatherDataDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public WeatherDataDao getWeatherDataDao() {
        return weatherDataDao;
    }

}
